name: 01-3 - Integration - Snyk

on:
  workflow_call

jobs:
  Quality_Snyk_Web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cesizen-web

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/php@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
