name: 01-3 - Integration - Snyk

on:
  workflow_call

jobs:
  Quality_Snyk_Web:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Snyk CLI
        uses: snyk/actions/setup@master

      - name: Run Snyk test (cesizen-web)
        working-directory: cesizen-web
        run: snyk test --severity-threshold=high
