name: 02-3 - Deploy

on:
  workflow_call

jobs:
  Deploy_Render:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render deploy
        run: curl -fsS -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
