name: 02 - Deployment

on:
  push:
    branches:
      - develop
      - main

jobs:
  Build_Push_Docker:
    if: ${{ github.ref_name == 'develop' }}
    uses: ./.github/workflows/02-1_docker-ghcr.yml
    permissions:
      contents: read
      packages: write

  Trivy_Scan_Package:
    needs: [Build_Push_Docker]
    uses: ./.github/workflows/02-2_trivy-scan.yml
    permissions:
      packages: read

  # ---------------------------------------------------

  Deploy:
    if: ${{ github.ref_name == 'main' }}
    uses: ./.github/workflows/02-3_deploy.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      packages: read

  Zap_Scan:
    needs: [Deploy]
    uses: ./.github/workflows/02-4_zap-scan.yml
    with:
      target-host: ${{ needs.Deploy.outputs.vm-hostname }}
    permissions:
      issues: write
